use-configs:                
  - lint/opensource/copyrights   
  - lint/opensource/banned_words 
lint:
  clang-format:
    included:
      - \.cpp$
      - \.h$
      - \.inl$
      - \.hpp$
    excluded:
      - third_party/
      - scripts/

  cmake-format:
    included:
      - CMakeLists.txt$
      - \.cmake$
    excluded:
      - third_party/*

  copyright:
    excluded:
      - third_party/
    mit_header:
      year_constraints:
        _default: 2022
      file_types:
        bat:
          comment_begin: "REM"
          comment_end: "REM"
          comment_char: "REM"

  ults-needed:
    disabled: true

  banned_words:
    master:
      todo:
