#
# Copyright (C) 2022-2024 Intel Corporation
#
# SPDX-License-Identifier: MIT
#

list(APPEND ALL_CORE_TYPES "GEN12LP")
list(APPEND ALL_CORE_TYPES "XE_HPG_CORE")
list(APPEND ALL_CORE_TYPES "XE_HPC_CORE")
list(APPEND ALL_CORE_TYPES "XE2_HPG_CORE")
list(APPEND ALL_CORE_TYPES "XE3_CORE")
